/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  life:[
    {
      type: 'category',
      label: '运动',
      items: [
        'life/sport/sport',
        'life/sport/badminton',
        // 'life/log',
        // 'life/travel/WugongMountain'
      ],
    },
  ],
  tutorialSidebar: [
    'introduction',
    // javaScript
    {
      type: 'category',
      label: 'javaScript',
      link: {
        type: 'generated-index', // 引导页类型
        title: 'javaScript', //名称
        description: 'javaScript总结', //描述
        slug: '/knowledgeStructure/docusaurus-javascript', //显示路径
        keywords: ['guides'], //标签
      },
      items: [
        'knowledgeStructure/javaScript/ES6',
      ],
    },
      // vue
    {
      type: 'category',
      label: 'vue',
      link: {
        type: 'generated-index', // 引导页类型
        title: 'vue引导页', //名称
        description: '这是一个引导页面', //描述
        slug: '/knowledgeStructure/docusaurus-vue', //显示路径
        keywords: ['guides'], //标签
      },
      items: [
        'knowledgeStructure/vue/test',
        'knowledgeStructure/vue/vue'
      ],
    },
      // node
    {
      type: 'category',
      label: 'node',
      link: {
        type: 'generated-index', // 引导页类型
        title: 'node', //名称
        description: 'node', //描述
        slug: '/knowledgeStructure/docusaurus-node', //显示路径
        keywords: ['guides'], //标签
      },
      items: [
        'knowledgeStructure/node/OBS',
        'knowledgeStructure/node/koa2',
      ],
    },
  ],
  log:[
    {
      type: 'category',
      label: '2023-11',
      link: {
        type: 'generated-index', // 引导页类型
        title: '2023-11', //名称
        description: '2023-11日记', //描述
        slug: '/log/2023-11', //显示路径
        keywords: ['guides'], //标签
      },
      items: [
        'log/2023-11/13',
        'log/2023-11/25',
        'log/2023-11/29',
      ],
    },
    {
      type: 'category',
      label: '2023-12',
      link: {
        type: 'generated-index', // 引导页类型
        title: '2023-12', //名称
        description: '2023-12总结', //描述
        slug: '/log/2023-12', //显示路径
        keywords: ['guides'], //标签
      },
      items: [
        'log/2023-12/12',
        'log/2023-12/19',
      ],
    },
    {
      type: 'category',
      label: '2024-2',
      link: {
        type: 'generated-index', // 引导页类型
        title: '2024-2', //名称
        description: '2024-2总结', //描述
        slug: '/log/2024-2', //显示路径
        keywords: ['guides'], //标签
      },
      items: [
        'log/2024-2/4',
        'log/2024-2/26',
      ],
    },
    {
      type: 'category',
      label: '2024-3',
      link: {
        type: 'generated-index', // 引导页类型
        title: '2024-3', //名称
        description: '2024-3总结', //描述
        slug: '/log/2024-3', //显示路径
        keywords: ['guides'], //标签
      },
      items: [
        'log/2024-3/8',
        'log/2024-3/12',
      ],
    },
      // 24年11月
    {
      type: 'category',
      label: '2024-11',
      link: {
        type: 'generated-index', // 引导页类型
        title: '2024-11', //名称
        description: '2024-11总结', //描述
        slug: '/log/2024-11', //显示路径
        keywords: ['guides'], //标签
      },
      items: [
        'log/2024-11/13',
        'log/2024-11/15',
      ],
    },
   //2025年1月
    {
      type: 'category',
      label: '2025-1',
      link: {
        type: 'generated-index', // 引导页类型
        title: '2025-1', //名称
        description: '2025-1总结', //描述
        slug: '/log/2025-1', //显示路径
        keywords: ['guides'], //标签
      },
      items: [
        'log/2025-1/13',
      ],
    },
    //2025年3月
    {
      type: 'category',
      label: '2025-3',
      link: {
        type: 'generated-index', // 引导页类型
        title: '2025-3', //名称
        description: '2025-3总结', //描述
        slug: '/log/2025-3', //显示路径
        keywords: ['guides'], //标签
      },
      items: [
        'log/2025-3/11',
      ],
    },
  ]
};

module.exports = sidebars;
